/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/ui/BottomSheet.vue')['default']
    ColorizeText: typeof import('./src/components/ui/ColorizeText.vue')['default']
    ConfirmationDialog: typeof import('./src/components/ui/ConfirmationDialog.vue')['default']
    CountSelector: typeof import('./src/components/ui/CountSelector.vue')['default']
    Loader: typeof import('./src/components/ui/Loader.vue')['default']
    NominationForm: typeof import('./src/components/NominationForm.vue')['default']
    ParticipantList: typeof import('./src/components/ParticipantList.vue')['default']
    RankedCheckBox: typeof import('./src/components/ui/RankedCheckBox.vue')['default']
    ResultCard: typeof import('./src/components/ui/ResultCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/ui/SnackBar.vue')['default']
  }
}
